# Generated by Django 4.2.3 on 2023-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_created_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=models.Model, related_name='post_comments', to='posts.post', verbose_name='Пост'),
        ),
    ]
